### ISSUE TITLE
change reaction order ?play

### ISSUE THREAD

**Issue by Profxy** [LupoBot/LupoBot#141]
### What is the suggestion about?

The order of the reactions at ?play <Songname> should be reversed. 
Now its 9, 8, 7, ... and it would be better if it's 1, 2, 3, ...

### Why should we add this feature?

because usually you want to choose the first song in the list and then you have to wait until the 1 appears.

### Additional information

![image](https://user-images.githubusercontent.com/43417353/140529631-84ccff9c-631c-4f1d-bd37-72e5bb9ddf18.png)

**Comment by Nick-kel** [comment]
Needs to be fixed in the library we use
