### ISSUE TITLE
?reactionroles not working

### ISSUE THREAD

**Issue by Profxy** [LupoBot/LupoBot#156]
### How the bug can be reproduced?

Try to create a message with reactionroles

### What behaviour would normally be expected?

you should be able to create a message with reactionroles

### When did the problem occur?

08.01.2022 00:19

### Additional information

![testing - Discord 08 01 2022 00_24_45](https://user-images.githubusercontent.com/43417353/148619834-c9844d58-53ec-4b31-b571-cf44706df44e.png)

**Comment by Nick-kel** [comment]
Incorrect usage
